package com.example.mapped.model;

public enum ServiceType {
    FOOD_SUPPORT,
    SKILL_TRAINING,
    DISCOUNT_FOOD_SALE,
    CLOTHING,
    HEALTH,
    PSYCHOTHERAPY,
    EMPLOYMENT,
    SHELTER,
    EDUCATIONAL_SUPPORT,
    TRANSLATION_SERVICES,
    LEGAL_SERVICES,
    GROUP_THERAPY, COUNSELING, THERAPY, SUPPORT_FOR_DIFFERENTLY_ABLED
}